name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Test
      run: mvn test
      
    - name: Bump patch version
      id: version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        IFS='.' read -ra V <<< "$VERSION"
        NEW_VERSION="${V[0]}.${V[1]}.$((V[2] + 1))"
        mvn versions:set -DnewVersion=$NEW_VERSION
        mvn versions:commit
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        
    - name: Build
      run: mvn package -DskipTests
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build and push Docker image
      run: |
        IMAGE="arkv1dev/simple-java-maven-app:${{ steps.version.outputs.version }}"
        docker build -t $IMAGE .
        docker push $IMAGE
        docker tag $IMAGE arkv1dev/simple-java-maven-app:latest
        docker push arkv1dev/simple-java-maven-app:latest
        
    - name: Deploy and test
      run: |
        docker run --rm arkv1dev/simple-java-maven-app:latest | grep "Hello World!"
        
    - name: Commit version
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add pom.xml
        git commit -m "Bump version to ${{ steps.version.outputs.version }}"
        git push